In [142]:
import pandas as pd
import numpy as np

import openpyxl
from openpyxl.styles import Font
from openpyxl.utils.dataframe import dataframe_to_rows

from docx import Document
from docx.shared import RGBColor
from docx.shared import Pt
from docx.oxml import OxmlElement
from docx.oxml.ns import nsdecls

In [7]:
df = pd.read_excel(r"M:\Zach Hatzenbeller\newsletter_scripts\Convert Excel to Word_v6_speediest.xlsm")
df["Asset"] = pd.Series(df["Asset"]).fillna(method='ffill')
df.head()

,Asset,Department,"Current status (clinical trials, process development)",Ongoing studies,Monthly Accomplishments,Ongoing Challenges
0,Dostarlimab,Upstream,The Dostarlimab Process Upstream Team successf...,A follow-up 200L SUB demonstration batch is un...,The team is pleased with completing the first ...,"Key concerns remain around FM1 production, par..."
1,Dostarlimab,Downstream,Successful completion of a 200L demonstration ...,A number of follow-up studies were identified ...,Successful completion of the 200L batch throug...,Migration of WuXi PC data to internal reposito...
2,Dostarlimab,Viral Clearance,No Update,No Update,No Update,No Update
3,Depemokimab,Upstream,No Update,No Update,No Update,No Update
4,Depemokimab,Downstream,Post PPQ and BLA filing,Bufer stability. Excipient investigation.,Post PPQ and deviation discussion. Update SSMQ...,Working with DSG (Kent) for reports to align w...

In [9]:
excel_file = r"M:\Zach Hatzenbeller\newsletter_scripts\Convert Excel to Word_v6_speediest.xlsm"
workbook = openpyxl.load_workbook(excel_file)
sheet = workbook.active

In [13]:
def dataframe_to_excel(df):
    wb = openpyxl.Workbook()
    ws = wb.active

    for r in dataframe_to_rows(df, index=True, header=True):
        ws.append(r)

    return wb

def excel_to_word(excel_file, word_file):
    # Open the Excel workbook
    workbook = openpyxl.load_workbook(excel_file)
    sheet = workbook.active

    # Create a new Word document
    doc = Document()

    # Get the dimensions of the Excel table
    num_rows = sheet.max_row
    num_cols = sheet.max_column

In [143]:
# Define a custom style with bold and italic attributes
def add_custom_style(doc, style_id, name, base_style=None):
    element = OxmlElement('w:style')
    element.set(nsdecls('w'), 'type', 'paragraph')
    element.set(nsdecls('w'), 'styleId', style_id)

    name_element = OxmlElement('w:name')
    name_element.set(nsdecls('w'), 'val', name)
    element.append(name_element)

    if base_style is not None:
        base_style_element = OxmlElement('w:basedOn')
        base_style_element.set(nsdecls('w'), 'val', base_style)
        element.append(base_style_element)

    run_properties = OxmlElement('w:rPr')
    bold_element = OxmlElement('w:b')
    bold_element.set(nsdecls('w'), 'val')
    italic_element = OxmlElement('w:i')
    italic_element.set(nsdecls('w'), 'val')
    run_properties.append(bold_element)
    run_properties.append(italic_element)
    element.append(run_properties)

    doc.styles._element.append(element)
    doc.styles._update_styles()

In [151]:
worksheet = dataframe_to_excel(df)

# Open the Excel workbook
sheet = worksheet.active

# Create a new Word document
doc = Document()

# Get the dimensions of the Excel table
num_rows = sheet.max_row
num_cols = sheet.max_column

len(df["Asset"].unique())

# Create a Word table with the same dimensions as the Excel table
table = doc.add_table(rows=num_rows, cols=2)
table.style = 'Table Grid'
table.allow_autofit = False

yellow = openpyxl.styles.colors.Color(rgb='FFFF00')

# Loop through each cell in the Excel table and copy its value and format to the Word table
table_row = 3
for count, row in enumerate(sheet.iter_rows(min_row=3, max_row=num_rows-1, min_col=1, max_col=num_cols)):
    
    table.cell(row_idx=count+3, col_idx=0).text = str(sheet.cell(row=table_row, column=2).value)
    table.cell(row_idx=count+3, col_idx=0).text.font.bold = True
            # table.cell(row_idx=cell.row, col_idx=1).text = str(cell.value)
            # # Copy cell value
            # # Copy cell font color and format
            # font = Font(color=yellow,
            #             bold=cell.font.bold,
            #             italic=cell.font.italic,
            #             underline=cell.font.underline)
    # Add a new paragraph to the cell
    paragraph = table.cell(row_idx=count+3, col_idx=1).add_paragraph()

    # Add text to the paragraph
    run_head1 = paragraph.add_run(str(sheet.cell(row=1, column=4).value))
    paragraph.add_run("\n")
    run_up1 = paragraph.add_run("Upstream: ")
    run_text1 = paragraph.add_run(str(sheet.cell(table_row,4).value))
    paragraph.add_run("\n")

    run_down1 = paragraph.add_run("Downstream: ")
    run_text2 = paragraph.add_run(str(sheet.cell(table_row+1,4).value))
    paragraph.add_run("\n")
    
    run_vc1 = paragraph.add_run("Viral Clearance: ")
    run_text3 = paragraph.add_run(str(sheet.cell(table_row+2,4).value))
    paragraph.add_run("\n")


    run_head2 = paragraph.add_run(str(sheet.cell(row=1, column=5).value))
    paragraph.add_run("\n")
    run_up2 = paragraph.add_run("Upstream: ")
    run_text4 = paragraph.add_run(str(sheet.cell(table_row,5).value))
    paragraph.add_run("\n")

    run_down2 = paragraph.add_run("Downstream: ")
    run_text5 = paragraph.add_run(str(sheet.cell(table_row+1,5).value))
    paragraph.add_run("\n")
    
    run_vc2 = paragraph.add_run("Viral Clearance: ")
    run_text6 = paragraph.add_run(str(sheet.cell(table_row+2,5).value))
    paragraph.add_run("\n")


    run_head3 = paragraph.add_run(str(sheet.cell(row=1, column=6).value))
    paragraph.add_run("\n")
    run_up3 = paragraph.add_run("Upstream: ")
    run_text7 = paragraph.add_run(str(sheet.cell(table_row,6).value))
    paragraph.add_run("\n")

    run_down3 = paragraph.add_run("Downstream: ")
    run_text8 = paragraph.add_run(str(sheet.cell(table_row+1,6).value))
    paragraph.add_run("\n")
    
    run_vc3 = paragraph.add_run("Viral Clearance: ")
    run_text9 = paragraph.add_run(str(sheet.cell(table_row+2,6).value))
    paragraph.add_run("\n")


    run_head4 = paragraph.add_run(str(sheet.cell(row=1, column=7).value))
    paragraph.add_run("\n")
    run_up4 = paragraph.add_run("Upstream: ")
    run_text10 = paragraph.add_run(str(sheet.cell(table_row,7).value))
    paragraph.add_run("\n")

    run_down4 = paragraph.add_run("Downstream: ")
    run_text11 = paragraph.add_run(str(sheet.cell(table_row+1,7).value))
    paragraph.add_run("\n")
    
    run_vc4 = paragraph.add_run("Viral Clearance: ")
    run_text12 = paragraph.add_run(str(sheet.cell(table_row+2,7).value))
    paragraph.add_run("\n")

    table_row += 3

    # Set the formatting for the paragraph
    paragraph_format = paragraph.paragraph_format

    run_heads = [run_head1,run_head2,run_head3,run_head4]
    run_up = [run_up1,run_up2,run_up3,run_up4]
    run_down = [run_down1,run_down2,run_down3,run_down4]
    run_vc = [run_vc1,run_vc2,run_vc3,run_vc4]
    run_text = [run_text1,run_text2,run_text3,run_text4,run_text5,run_text6,run_text7,run_text8,run_text9,run_text10,run_text11,run_text12]


    for i in run_heads:
        # Apply font styling to the run
        font = i.font
        font.name = 'Arial Narrow'
        # Set the font size (e.g., 12pt)
        font.size = Pt(12)
        # Set the font color (e.g., red)
        font.color.rgb = RGBColor(0, 0, 0)  # RGBColor(red, green, blue)
        # Apply bold and italic styles
        font.bold = True
        font.italic = False
        font.underline = True
    
    for i in run_up:
        # Apply font styling to the run
        font = i.font
        font.name = 'Arial Narrow'
        # Set the font size (e.g., 12pt)
        font.size = Pt(10)
        # Set the font color (e.g., red)
        font.color.rgb = RGBColor(255, 102, 0)  # RGBColor(red, green, blue)
        # Apply bold and italic styles
        font.bold = True
        font.italic = True

    for i in run_down:
        # Apply font styling to the run
        font = i.font
        font.name = 'Arial Narrow'
        # Set the font size (e.g., 12pt)
        font.size = Pt(10)
        # Set the font color (e.g., red)
        font.color.rgb = RGBColor(3, 37, 126)  # RGBColor(red, green, blue)
        # Apply bold and italic styles
        font.bold = True
        font.italic = True
    
    for i in run_vc:
        # Apply font styling to the run
        font = i.font
        font.name = 'Arial Narrow'
        # Set the font size (e.g., 12pt)
        font.size = Pt(10)
        # Set the font color (e.g., red)
        font.color.rgb = RGBColor(128, 0, 128)  # RGBColor(red, green, blue)
        # Apply bold and italic styles
        font.bold = True
        font.italic = True
    
    for i in run_text:
        # Apply font styling to the run
        font = i.font
        font.name = 'Arial Narrow'
        # Set the font size (e.g., 12pt)
        font.size = Pt(10)
        # Set the font color (e.g., red)
        font.color.rgb = RGBColor(0, 0, 0)  # RGBColor(red, green, blue)
        # Apply bold and italic styles

# for row in table.rows:
#     for cell in row.cells:
#         paragraphs = cell.paragraphs
#         paragraph = paragraphs[0]
#         run_obj = paragraph.runs
#         run = run_obj[0]
#         font = run.font
#         # font.size = Pt(30)

# Save the Word document
doc.save(r"M:\Zach Hatzenbeller\newsletter_scripts\Test.docx")

In [132]:
sheet.cell(1,3)

In [69]:
df

,Asset,Department,"Current status (clinical trials, process development)",Ongoing studies,Monthly Accomplishments,Ongoing Challenges
0,Dostarlimab,Upstream,The Dostarlimab Process Upstream Team successf...,A follow-up 200L SUB demonstration batch is un...,The team is pleased with completing the first ...,"Key concerns remain around FM1 production, par..."
1,Dostarlimab,Downstream,Successful completion of a 200L demonstration ...,A number of follow-up studies were identified ...,Successful completion of the 200L batch throug...,Migration of WuXi PC data to internal reposito...
2,Dostarlimab,Viral Clearance,No Update,No Update,No Update,No Update
3,Depemokimab,Upstream,No Update,No Update,No Update,No Update
4,Depemokimab,Downstream,Post PPQ and BLA filing,Bufer stability. Excipient investigation.,Post PPQ and deviation discussion. Update SSMQ...,Working with DSG (Kent) for reports to align w...
...,...,...,...,...,...,...
58,PAPP-A,Downstream,No Update,No Update,No Update,No Update
59,PAPP-A,Viral Clearance,NaN,NaN,No Update,No Update
60,NA Flu mAb,Upstream,Vial thaw tentatively to be moved forward to 1...,No Update,Tech Transfer meetings started for TOX batch i...,Current CTM Thaw date is 09Oct2023 which gives...
61,NA Flu mAb,Downstream,No Update,No Update,No Update,No Update
62,NA Flu mAb,Viral Clearance,No Update,No Update,No Update,No Update